/**
 * Artifact Mapping Configuration (Legacy)
 *
 * Retained for backward compatibility with stored messages. All data skills
 * have migrated to MCP + canvas:html, so the mappings are now empty. New
 * conversations render free-form HTML via canvas:html blocks generated by
 * the model.
 */

import type { ArtifactType } from '@/shared/types/artifact';

type MappingType = ArtifactType | 'text';

export interface ToolMetadata {
  skill: string;
  action: string;
  list_code?: string;
}

const SKILL_ACTION_MAPPING: Record<string, Record<string, MappingType>> = {};
const SCREENER_LIST_CODE_MAPPING: Record<string, MappingType> = {};

export function determineArtifactType(
  metadata: ToolMetadata
): ArtifactType | null {
  const { skill, action, list_code } = metadata;
  if (!skill || !action) return null;

  if (action === 'query_list_data_by_date' && list_code) {
    const mapped = SCREENER_LIST_CODE_MAPPING[list_code];
    if (mapped && mapped !== 'text') return mapped;
    return null;
  }

  const skillMapping = SKILL_ACTION_MAPPING[skill];
  if (!skillMapping) return null;

  const artifactType = skillMapping[action];
  if (!artifactType || artifactType === 'text') return null;

  return artifactType;
}

export function parseToolMetadata(
  jsonStr: string | null | undefined
): ToolMetadata | null {
  if (!jsonStr) return null;
  try {
    return JSON.parse(jsonStr) as ToolMetadata;
  } catch {
    return null;
  }
}

export function serializeToolMetadata(metadata: ToolMetadata): string {
  return JSON.stringify(metadata);
}

export function getRegisteredArtifactTypes(): ArtifactType[] {
  return [];
}
